// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: receive/v1/receive.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationReceiveServiceReceive = "/receive.v1.ReceiveService/Receive"

type ReceiveServiceHTTPServer interface {
	// Receive Receive validates reported file information.
	Receive(context.Context, *ReceiveRequest) (*ReceiveReply, error)
}

func RegisterReceiveServiceHTTPServer(s *http.Server, srv ReceiveServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/receive", _ReceiveService_Receive0_HTTP_Handler(srv))
}

func _ReceiveService_Receive0_HTTP_Handler(srv ReceiveServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReceiveRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReceiveServiceReceive)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Receive(ctx, req.(*ReceiveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReceiveReply)
		return ctx.Result(200, reply)
	}
}

type ReceiveServiceHTTPClient interface {
	// Receive Receive validates reported file information.
	Receive(ctx context.Context, req *ReceiveRequest, opts ...http.CallOption) (rsp *ReceiveReply, err error)
}

type ReceiveServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewReceiveServiceHTTPClient(client *http.Client) ReceiveServiceHTTPClient {
	return &ReceiveServiceHTTPClientImpl{client}
}

// Receive Receive validates reported file information.
func (c *ReceiveServiceHTTPClientImpl) Receive(ctx context.Context, in *ReceiveRequest, opts ...http.CallOption) (*ReceiveReply, error) {
	var out ReceiveReply
	pattern := "/receive"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationReceiveServiceReceive))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
