// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: receive/v1/receive.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReceiveRequest represents the request to report file information.
type ReceiveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// StoreUrl
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// File hash (Hash)
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// Last Modified time
	Lm string `protobuf:"bytes,3,opt,name=lm,proto3" json:"lm,omitempty"`
	// Content Length
	Cl            uint64 `protobuf:"varint,4,opt,name=cl,proto3" json:"cl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_receive_v1_receive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receive_v1_receive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_receive_v1_receive_proto_rawDescGZIP(), []int{0}
}

func (x *ReceiveRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ReceiveRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ReceiveRequest) GetLm() string {
	if x != nil {
		return x.Lm
	}
	return ""
}

func (x *ReceiveRequest) GetCl() uint64 {
	if x != nil {
		return x.Cl
	}
	return 0
}

// ReceiveReply represents the response of file information reporting.
type ReceiveReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveReply) Reset() {
	*x = ReceiveReply{}
	mi := &file_receive_v1_receive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveReply) ProtoMessage() {}

func (x *ReceiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_receive_v1_receive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveReply.ProtoReflect.Descriptor instead.
func (*ReceiveReply) Descriptor() ([]byte, []int) {
	return file_receive_v1_receive_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiveReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_receive_v1_receive_proto protoreflect.FileDescriptor

const file_receive_v1_receive_proto_rawDesc = "" +
	"\n" +
	"\x18receive/v1/receive.proto\x12\n" +
	"receive.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1copenapi/v3/annotations.proto\"\xec\x03\n" +
	"\x0eReceiveRequest\x12e\n" +
	"\x03url\x18\x01 \x01(\tBS\xbaGP:)\x12'\"https://example.com/static/js/main.js\"\x92\x02\"The full URL of the file resource.R\x03url\x12q\n" +
	"\x04hash\x18\x02 \x01(\tB]\xbaGZ:$\x12\"\"d41d8cd98f00b204e9800998ecf8427e\"\x92\x021The HASH value of the file (e.g., MD5 or SHA256).R\x04hash\x12o\n" +
	"\x02lm\x18\x03 \x01(\tB_\xbaG\\:!\x12\x1f\"Wed, 21 Oct 2015 07:28:00 GMT\"\x92\x026The Last-Modified header value from the origin server.R\x02lm\x12F\n" +
	"\x02cl\x18\x04 \x01(\x04B6\xbaG3:\x06\x12\x041024\x92\x02(The Content-Length of the file in bytes.R\x02cl:G\xbaGD\x92\x02AReceiveRequest represents the request to report file information.\"\x98\x01\n" +
	"\fReceiveReply\x12=\n" +
	"\amessage\x18\x01 \x01(\tB#\xbaG :\x06\x12\x04\"ok\"\x92\x02\x15Confirmation message.R\amessage:I\xbaGF\x92\x02CReceiveReply represents the response of file information reporting.2\xd1\x01\n" +
	"\x0eReceiveService\x12\xbe\x01\n" +
	"\aReceive\x12\x1a.receive.v1.ReceiveRequest\x1a\x18.receive.v1.ReceiveReply\"}\xbaGg\x12!Receive reported file information\x1aBValidates reported file information against authoritative records.\x82\xd3\xe4\x93\x02\r:\x01*\"\b/receiveB\xc9\x02\xbaG\xd5\x01\x12\xd2\x01\n" +
	"\x0fReceive Service\x12@ReceiveService provides file consistency verification reporting.\"3\n" +
	"\aomalloc\x12(https://github.com/omalloc/trust-receive*A\n" +
	"\x03MIT\x12:https://github.com/omalloc/trust-receive/blob/main/LICENSE2\x051.0.0\n" +
	"(com.omalloc.trust-receive.api.receive.v1B\x0eReceiveProtoV1P\x01Z2github.com/omalloc/trust-receive/api/receive/v1;v1b\x06proto3"

var (
	file_receive_v1_receive_proto_rawDescOnce sync.Once
	file_receive_v1_receive_proto_rawDescData []byte
)

func file_receive_v1_receive_proto_rawDescGZIP() []byte {
	file_receive_v1_receive_proto_rawDescOnce.Do(func() {
		file_receive_v1_receive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_receive_v1_receive_proto_rawDesc), len(file_receive_v1_receive_proto_rawDesc)))
	})
	return file_receive_v1_receive_proto_rawDescData
}

var file_receive_v1_receive_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_receive_v1_receive_proto_goTypes = []any{
	(*ReceiveRequest)(nil), // 0: receive.v1.ReceiveRequest
	(*ReceiveReply)(nil),   // 1: receive.v1.ReceiveReply
}
var file_receive_v1_receive_proto_depIdxs = []int32{
	0, // 0: receive.v1.ReceiveService.Receive:input_type -> receive.v1.ReceiveRequest
	1, // 1: receive.v1.ReceiveService.Receive:output_type -> receive.v1.ReceiveReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_receive_v1_receive_proto_init() }
func file_receive_v1_receive_proto_init() {
	if File_receive_v1_receive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_receive_v1_receive_proto_rawDesc), len(file_receive_v1_receive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_receive_v1_receive_proto_goTypes,
		DependencyIndexes: file_receive_v1_receive_proto_depIdxs,
		MessageInfos:      file_receive_v1_receive_proto_msgTypes,
	}.Build()
	File_receive_v1_receive_proto = out.File
	file_receive_v1_receive_proto_goTypes = nil
	file_receive_v1_receive_proto_depIdxs = nil
}
