// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/omalloc/trust-receive/internal/biz"
	"github.com/omalloc/trust-receive/internal/conf"
	"github.com/omalloc/trust-receive/internal/data"
	"github.com/omalloc/trust-receive/internal/server"
	"github.com/omalloc/trust-receive/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	receiveRepo := data.NewReceiveRepo(dataData, logger)
	alerter := biz.NewAlerter(logger)
	receiveUsecase := biz.NewReceiveUsecase(receiveRepo, alerter, logger)
	receiveServiceService := service.NewReceiveServiceService(receiveUsecase)
	grpcServer := server.NewGRPCServer(confServer, receiveServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, receiveServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
